apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: demo
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/part-of: demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/part-of: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: http